### ISSUE TITLE
Fetch logs to process

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Turvis#12]
AS A Service Manager
I WANT to send a selection of raw logs for further processing
SO THAT I could focus only on processing the logs that interest me

#### Technical requirements

- [ ] `Docker Compose` to set everything up
- [ ] Any number of raw logs `source` can be defined without re-deploying or restarting the container

> For example, fetch both Ruuter and Resql logs

- [ ] All `source` must be matched with `destination`

> For example, Ruuter logs are stored in "logs/output/Ruuter/" and Resql logs in "logs/output/Resql/"

- [ ] External mounted volume is used as `destination`

#### Business requirements

- [ ] Use [Ruuter](https://github.com/buerokratt/Ruuter) raw logs as input
- [ ] Logs are transported from `source` to `destination`
- [ ] Logs are validated in their `destination`, not near real-time in `source`
- [ ] Different pattern matching rules can be applied on different `source` to `destination` rules

#### Technical stack

- [ ] Existing [ETL](https://en.wikipedia.org/wiki/Extract,_transform,_load) can be used
- [ ] [Logstash](https://www.elastic.co/logstash) is a good candidate
- [ ] Custom solution may be used
