### ISSUE TITLE
Pattern matching

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Turvis#3]
AS A Security Engineer
I WANT TO verify the given input against my pre-defined patterns
SO THAT I could automatically identify and stop potentially harmful requests

### Acceptance Criteria

- [ ] Pattern matching against JSON by #14
- [ ] Pattern matching against JSON by #17
- [ ] Verify a specific pattern against a specific part of the input
- [ ] ~Identify all matching patterns against a specific part of the input~
