### ISSUE TITLE
Turvis results on dashboard

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Turvis#31]
AS A SecOps / Dev Lead
I WANT to see Turvis' results on dashboard
SO THAT I would have a good overview of deviations from expected results

### Acceptance Criteria

- [ ] Output created by Turvis are used as source data
- [ ] If needed, output created by Turvis must be further processed to be machine-readable by the dashboards-providing software
- [ ] The software used to provide dashboards is a well-established out-of-the-box software
> To be confirmed with Bürokratt's architect
